name: Build Kernel A145P

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Samsung Kernel Source
        uses: actions/checkout@v4

      - name: Set up Environment & Sync AOSP Toolchains
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 git curl bc bison flex libssl-dev make zip nodejs python-is-python3
          
          # نصب ابزار repo گوگل برای دانلود یکپارچه محیط بیلد
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH="~/bin:$PATH"
          
          # تنظیمات ضروری گیت برای جلوگیری از ارور ابزار repo
          git config --global user.name "Behrooz140"
          git config --global user.email "behrooz140@local.dev"
          
          # دانلود یکپارچه تمام ابزارهای بیلد از گوگل (شاخه اندروید ۱۵ - کرنل ۶.۶)
          mkdir aosp_toolchain
          cd aosp_toolchain
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android15-6.6 --depth=1
          repo sync -c -j$(nproc) --no-clone-bundle --no-tags
          
          # کپی دقیق ۴ پوشه حیاتی به روت سورس سامسونگ (طبق دستورالعمل README)
          cd ..
          cp -r aosp_toolchain/build ./
          cp -r aosp_toolchain/external ./
          cp -r aosp_toolchain/prebuilts ./
          cp -r aosp_toolchain/tools ./

      - name: Build with Samsung Script
        run: |
          # ورود به پوشه کرنل طبق راهنمای سازنده
          cd kernel
          
          # ساخت فایل کانفیگ دقیقاً با آرگومان‌های مدیاتک/سامسونگ
          python3 kernel_device_modules-6.6/scripts/gen_build_config.py \
            --kernel-defconfig mediatek-bazel_defconfig \
            --kernel-defconfig-overlays "mt6768_overlay.config o22.config" \
            --kernel-build-config-overlays "" \
            -m user -o ../out/target/product/a14m/obj/KERNEL_OBJ/build.config
          
          # اعمال متغیرهای محیطی ضروری برای کامپایل
          export DEVICE_MODULES_DIR="kernel_device_modules-6.6"
          export BUILD_CONFIG="../out/target/product/a14m/obj/KERNEL_OBJ/build.config"
          export OUT_DIR="../out/target/product/a14m/obj/KLEAF_OBJ"
          export DIST_DIR="../out/target/product/a14m/obj/KLEAF_OBJ/dist"
          export DEFCONFIG_OVERLAYS="mt6768_overlay.config o22.config"
          export PROJECT="mgk_64_k66"
          export MODE="user"
          
          # اجرای اسکریپت اصلی بیلد سامسونگ
          chmod +x ./kernel_device_modules-6.6/build.sh
          ./kernel_device_modules-6.6/build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: A145P-Kernel-Output
          path: out/target/product/a14m/obj/KLEAF_OBJ/dist/*
